apiVersion: serving.knative.dev/v1alpha1
kind: Service
metadata:
  name: gorun
spec:
  runLatest:
    configuration:
      revisionTemplate:
        spec:
          container:
            image: gcr.io/cloudylabs-public/gorun:0.1.6
            resources:
              requests:
                cpu: "1"
              limits:
                cpu: "1"
